# Generated by Django 4.0.3 on 2022-04-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesaCoder', '0002_alter_familia_fechanac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='fechanac',
            field=models.DateField(auto_now=True),
        ),
    ]
